### ISSUE TITLE
Getting import error when using playAudit

### ISSUE THREAD

**Issue by digracesion** [abhinaba-ghosh/playwright-lighthouse#50]
Everytime I run my tests, I'm encountering the following error message:

```
SyntaxError: Unexpected token 'export'

      1 | import { test, chromium } from '@playwright/test';
    > 2 | import { playAudit } from 'playwright-lighthouse';
        | ^
      3 | import lighthouse from 'lighthouse';

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (resources/js/tests/e2e/audit.spec.ts:2:1)
```

But `package.json` shows `playwright-lighthouse": "^3.1.0`, so I'm quite confused as to what's wrong here.

**Comment by ahernd2** [comment]
Seeing same issue

**Comment by edumserrano** [comment]
I'm also getting this, seems like a duplicate of #45.

As suggested on the stackoverflow link provided on #45, adding:
```
"type": "module",
```

to my `package.json` solved the issue.

There's also [this question](https://github.com/abhinaba-ghosh/playwright-lighthouse/pull/46#issuecomment-1439885846) at #46 but there's no response so I'm not sure if there's an alternative to the solution above.

**Comment by abhishekjha7798** [comment]
What if someone does not want to add "type": "module" in their package.json because project is configured with commonjs? Do we have any other solution?

**Comment by alphonse92** [comment]
> What if someone does not want to add "type": "module" in their package.json because project is configured with commonjs? Do we have any other solution?

I posted my fix here without placing the "type" module

https://github.com/abhinaba-ghosh/playwright-lighthouse/issues/72
