### ISSUE TITLE
Lighthouse report is blank. I'm running my report in playwirght test runner with  vscode

### ISSUE THREAD

**Issue by potnoddle** [abhinaba-ghosh/playwright-lighthouse#73]
compiled-reportrenderer.js:2656  Uncaught Error: query .lh-category .lh-category-header not found
    at te.find (compiled-reportrenderer.js:2636:9257)
    at O.injectFinalScreenshot (compiled-reportrenderer.js:2636:21728)
    at ie._renderReport (compiled-reportrenderer.js:2637:2939)
    at ie.renderReport (compiled-reportrenderer.js:2636:59883)
    at Ne (compiled-reportrenderer.js:2637:18547)
    at Lt (compiled-reportrenderer.js:2666:527)
    at compiled-reportrenderer.js:2706:3

**Comment by damongabrielle** [comment]
I hit this issue as well with playwright-lighthouse `4.0.0`, playwright `1.46.1` and lighthouse `12.2.1`.

Took me a while to figure out what was going on. It should be reproducible if you don't set thresholds for any category.  

This playwrightLighthouseConfig produced the above error:

```
const playwrightLighthouseConfig = {
    ignoreError: true,
    reports: {
        formats: {
            json: true,
            html: true,
            csv: true,
        },
        name: 'lighthouse-default-report',
        directory: `${process.cwd()}/lighthouse-report`
    },
    port: 9222,
    thresholds: {}
};
```

and this one works:

```
const playwrightLighthouseConfig = {
    ignoreError: true,
    reports: {
        formats: {
            json: true,
            html: true,
            csv: true,
        },
        name: 'lighthouse-default-report',
        directory: `${process.cwd()}/lighthouse-report`
    },
    port: 9222,
    thresholds: {
      performance: 0
    }
};
```

Note: I'm setting IgnoreError so I can get the report back regardless of whether there's a failure so I can make custom reports before re-throwing the error. I don't think its related to the problem but also didn't investigate.
